<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1a697209-f1e6-4392-bc72-2d64fc22027c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\channel.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\server.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.80.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.80.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
