syntax = "proto3";

option csharp_namespace = "Community_Service";

package Channel_Service;

// The greeting service definition.
service Channel_Service {
  rpc CreateChannel (ChannelRequest) returns (ChannelResponse);
  rpc UpdateChannel (ChannelRequest) returns (ChannelResponse);
  rpc DeleteChannel (ChannelDeleteRequest) returns (LittelChannelResponse);
  //rpc GetChannel (ChannelRequest) returns (ChannelResponse);
  
}


message ChannelRequest {
  string name = 1;
  string type = 2;
  int64 ServerId = 3;
}

message ChannelResponse {
  int64 id = 1;
  string name = 2;
  string type = 3;
  int64 ServerId = 4;
}

message ChannelDeleteRequest {
  int64 id = 1;
  string comand = 2; // команда для удаления канала, будет типа delete {channel_name}
  string type = 3; // тип канала, будет типа text или voice
}

message LittelChannelResponse {
  string message = 1;
}