syntax = "proto3";

import "Protos/channel.proto";

option csharp_namespace = "Community_Service";

package Server_Service;


service Server_Service {
	rpc CreateServer (ServiceRequest) returns (ServiceResponse);
	rpc UpdateServer (ServiceRequest) returns (ServiceResponse);
	rpc DeleteServer (ServiceDeleteRequest) returns (LittelResponse);
	rpc AddUser (AddUserRequest) returns (ServiceResponse);
	rpc GetServer (ServiceDeleteRequest) returns (ServiceResponse);
 
}

message ServiceRequest {
  int64 id = 1;
  string name = 2;
  string description =3;
  string image = 4;
}

message ServiceResponse {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string Image = 4;
  repeated Channel_Service.ChannelResponse channels = 5;
  repeated int64 users = 6;
}

message ServiceDeleteRequest {
  int64 id = 1;
  string comand = 2;// команда для удаления сервера, будет типа delete {server_name}
}
message LittelResponse {
  string message = 1;
}
message AddUserRequest {
  int64 serverId = 1;
  int64 userId = 2;
}