-- IDs for communities and channels are now generated by the application.
-- Existing values and foreign keys remain unchanged.
ALTER TABLE communities ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE channels ALTER COLUMN id DROP IDENTITY IF EXISTS;
